services:
  - type: web
    name: devheat-codecolab
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: daphne collaborative_code_editor.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: devheat-codecolab.onrender.com
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    healthCheckPath: /
    autoDeploy: true
