services:
  - type: web
    name: devheat-codecodelab
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn collaborative_code_editor.wsgi
