# Generated by Django 5.1.4 on 2024-12-21 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_editor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coderoom",
            name="creator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
